
package ehealth.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HealthProfile", targetNamespace = "http://ws.ehealth/", wsdlLocation = "http://localhost:8000/ehealth/LifestyleCoach?wsdl")
public class HealthProfile
    extends Service
{

    private final static URL HEALTHPROFILE_WSDL_LOCATION;
    private final static WebServiceException HEALTHPROFILE_EXCEPTION;
    private final static QName HEALTHPROFILE_QNAME = new QName("http://ws.ehealth/", "HealthProfile");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8000/ehealth/LifestyleCoach?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HEALTHPROFILE_WSDL_LOCATION = url;
        HEALTHPROFILE_EXCEPTION = e;
    }

    public HealthProfile() {
        super(__getWsdlLocation(), HEALTHPROFILE_QNAME);
    }

    public HealthProfile(WebServiceFeature... features) {
        super(__getWsdlLocation(), HEALTHPROFILE_QNAME, features);
    }

    public HealthProfile(URL wsdlLocation) {
        super(wsdlLocation, HEALTHPROFILE_QNAME);
    }

    public HealthProfile(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HEALTHPROFILE_QNAME, features);
    }

    public HealthProfile(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HealthProfile(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LifeCoach
     */
    @WebEndpoint(name = "LifestyleCoachImplPort")
    public LifeCoach getLifestyleCoachImplPort() {
        return super.getPort(new QName("http://ws.ehealth/", "LifestyleCoachImplPort"), LifeCoach.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LifeCoach
     */
    @WebEndpoint(name = "LifestyleCoachImplPort")
    public LifeCoach getLifestyleCoachImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.ehealth/", "LifestyleCoachImplPort"), LifeCoach.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HEALTHPROFILE_EXCEPTION!= null) {
            throw HEALTHPROFILE_EXCEPTION;
        }
        return HEALTHPROFILE_WSDL_LOCATION;
    }

}
