
package ehealth.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LifeCoach", targetNamespace = "http://ws.ehealth/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LifeCoach {


    /**
     * 
     * @param username
     * @param key
     * @return
     *     returns ehealth.ws.Goal
     */
    @WebMethod(operationName = "GetPushMessage")
    @WebResult(name = "PushMessage", targetNamespace = "")
    @RequestWrapper(localName = "GetPushMessage", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetPushMessage")
    @ResponseWrapper(localName = "GetPushMessageResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetPushMessageResponse")
    @Action(input = "http://ws.ehealth/LifeCoach/GetPushMessageRequest", output = "http://ws.ehealth/LifeCoach/GetPushMessageResponse")
    public Goal getPushMessage(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @param username
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "shareLifeStatus", targetNamespace = "")
    @RequestWrapper(localName = "shareLifeStatus", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.ShareLifeStatus")
    @ResponseWrapper(localName = "shareLifeStatusResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.ShareLifeStatusResponse")
    @Action(input = "http://ws.ehealth/LifeCoach/shareLifeStatusRequest", output = "http://ws.ehealth/LifeCoach/shareLifeStatusResponse")
    public String shareLifeStatus(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @param username
     * @param key
     * @return
     *     returns java.util.List<ehealth.ws.LifeStatus>
     */
    @WebMethod
    @WebResult(name = "viewLifeStatus", targetNamespace = "")
    @RequestWrapper(localName = "viewLifeStatus", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.ViewLifeStatus")
    @ResponseWrapper(localName = "viewLifeStatusResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.ViewLifeStatusResponse")
    @Action(input = "http://ws.ehealth/LifeCoach/viewLifeStatusRequest", output = "http://ws.ehealth/LifeCoach/viewLifeStatusResponse")
    public List<LifeStatus> viewLifeStatus(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @param username
     * @param key
     * @return
     *     returns java.util.List<ehealth.ws.Goal>
     */
    @WebMethod
    @WebResult(name = "CurrentGoal", targetNamespace = "")
    @RequestWrapper(localName = "getCurrentGoal", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetCurrentGoal")
    @ResponseWrapper(localName = "getCurrentGoalResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetCurrentGoalResponse")
    @Action(input = "http://ws.ehealth/LifeCoach/getCurrentGoalRequest", output = "http://ws.ehealth/LifeCoach/getCurrentGoalResponse")
    public List<Goal> getCurrentGoal(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @return
     *     returns java.util.List<ehealth.ws.MeasureDefinition>
     */
    @WebMethod
    @WebResult(name = "Measures", targetNamespace = "")
    @RequestWrapper(localName = "getMeasuresDefinition", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetMeasuresDefinition")
    @ResponseWrapper(localName = "getMeasuresDefinitionResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetMeasuresDefinitionResponse")
    @Action(input = "http://ws.ehealth/LifeCoach/getMeasuresDefinitionRequest", output = "http://ws.ehealth/LifeCoach/getMeasuresDefinitionResponse")
    public List<MeasureDefinition> getMeasuresDefinition();

    /**
     * 
     * @param username
     * @param key
     * @return
     *     returns ehealth.ws.UserProfile
     */
    @WebMethod
    @WebResult(name = "profile", targetNamespace = "")
    @RequestWrapper(localName = "getUserProfile", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetUserProfile")
    @ResponseWrapper(localName = "getUserProfileResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetUserProfileResponse")
    @Action(input = "http://ws.ehealth/LifeCoach/getUserProfileRequest", output = "http://ws.ehealth/LifeCoach/getUserProfileResponse")
    public UserProfile getUserProfile(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMotivation")
    @WebResult(name = "Motivation", targetNamespace = "")
    @RequestWrapper(localName = "GetMotivation", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetMotivation")
    @ResponseWrapper(localName = "GetMotivationResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetMotivationResponse")
    @Action(input = "http://ws.ehealth/LifeCoach/GetMotivationRequest", output = "http://ws.ehealth/LifeCoach/GetMotivationResponse")
    public String getMotivation();

    /**
     * 
     * @param username
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "shareGoal", targetNamespace = "")
    @RequestWrapper(localName = "shareGoal", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.ShareGoal")
    @ResponseWrapper(localName = "shareGoalResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.ShareGoalResponse")
    @Action(input = "http://ws.ehealth/LifeCoach/shareGoalRequest", output = "http://ws.ehealth/LifeCoach/shareGoalResponse")
    public String shareGoal(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @param username
     * @param measureType
     * @param value
     * @param key
     * @return
     *     returns ehealth.ws.LifeStatus
     */
    @WebMethod
    @WebResult(name = "LifeStatus", targetNamespace = "")
    @RequestWrapper(localName = "addLifeStatus", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.AddLifeStatus")
    @ResponseWrapper(localName = "addLifeStatusResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.AddLifeStatusResponse")
    @Action(input = "http://ws.ehealth/LifeCoach/addLifeStatusRequest", output = "http://ws.ehealth/LifeCoach/addLifeStatusResponse")
    public LifeStatus addLifeStatus(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key,
        @WebParam(name = "value", targetNamespace = "")
        Double value,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType);

    /**
     * 
     * @param username
     * @param goalId
     * @param key
     * @return
     *     returns ehealth.ws.Goal
     */
    @WebMethod
    @WebResult(name = "setGoal", targetNamespace = "")
    @RequestWrapper(localName = "setGoal", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.SetGoal")
    @ResponseWrapper(localName = "setGoalResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.SetGoalResponse")
    @Action(input = "http://ws.ehealth/LifeCoach/setGoalRequest", output = "http://ws.ehealth/LifeCoach/setGoalResponse")
    public Goal setGoal(
        @WebParam(name = "GoalId", targetNamespace = "")
        Goal goalId,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @param username
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "login", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.LoginResponse")
    @Action(input = "http://ws.ehealth/LifeCoach/loginRequest", output = "http://ws.ehealth/LifeCoach/loginResponse")
    public String login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param username
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "logout", targetNamespace = "")
    @RequestWrapper(localName = "logout", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.LogoutResponse")
    @Action(input = "http://ws.ehealth/LifeCoach/logoutRequest", output = "http://ws.ehealth/LifeCoach/logoutResponse")
    public String logout(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "Key", targetNamespace = "")
        String key);

    /**
     * 
     * @param user
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "NewUser", targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.CreateUserResponse")
    @Action(input = "http://ws.ehealth/LifeCoach/createUserRequest", output = "http://ws.ehealth/LifeCoach/createUserResponse")
    public int createUser(
        @WebParam(name = "user", targetNamespace = "")
        UserProfile user);

    /**
     * 
     * @param uid
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "deleteUser", targetNamespace = "")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.DeleteUserResponse")
    @Action(input = "http://ws.ehealth/LifeCoach/deleteUserRequest", output = "http://ws.ehealth/LifeCoach/deleteUserResponse")
    public int deleteUser(
        @WebParam(name = "Uid", targetNamespace = "")
        int uid);

    /**
     * 
     * @param username
     * @param key
     * @param goal
     * @return
     *     returns ehealth.ws.Goal
     */
    @WebMethod(operationName = "GoalUpdate")
    @WebResult(name = "GoalUpdate", targetNamespace = "")
    @RequestWrapper(localName = "GoalUpdate", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GoalUpdate")
    @ResponseWrapper(localName = "GoalUpdateResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GoalUpdateResponse")
    @Action(input = "http://ws.ehealth/LifeCoach/GoalUpdateRequest", output = "http://ws.ehealth/LifeCoach/GoalUpdateResponse")
    public Goal goalUpdate(
        @WebParam(name = "goal", targetNamespace = "")
        Goal goal,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @param username
     * @param user
     * @param key
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "updateUser", targetNamespace = "")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.UpdateUserResponse")
    @Action(input = "http://ws.ehealth/LifeCoach/updateUserRequest", output = "http://ws.ehealth/LifeCoach/updateUserResponse")
    public int updateUser(
        @WebParam(name = "user", targetNamespace = "")
        UserProfile user,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @return
     *     returns java.util.List<ehealth.ws.UserProfile>
     */
    @WebMethod
    @WebResult(name = "Users", targetNamespace = "")
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetAllUsersResponse")
    @Action(input = "http://ws.ehealth/LifeCoach/getAllUsersRequest", output = "http://ws.ehealth/LifeCoach/getAllUsersResponse")
    public List<UserProfile> getAllUsers();

    /**
     * 
     * @param username
     * @param key
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "loginCheck", targetNamespace = "")
    @RequestWrapper(localName = "loginCheck", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.LoginCheck")
    @ResponseWrapper(localName = "loginCheckResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.LoginCheckResponse")
    @Action(input = "http://ws.ehealth/LifeCoach/loginCheckRequest", output = "http://ws.ehealth/LifeCoach/loginCheckResponse")
    public int loginCheck(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @param username
     * @param goalid
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "deleteGoal", targetNamespace = "")
    @RequestWrapper(localName = "deleteGoal", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.DeleteGoal")
    @ResponseWrapper(localName = "deleteGoalResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.DeleteGoalResponse")
    @Action(input = "http://ws.ehealth/LifeCoach/deleteGoalRequest", output = "http://ws.ehealth/LifeCoach/deleteGoalResponse")
    public String deleteGoal(
        @WebParam(name = "Goalid", targetNamespace = "")
        int goalid,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

}
