
package ehealth.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LifestyleCoach", targetNamespace = "http://ws.ehealth/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LifestyleCoach {


    /**
     * 
     * @return
     *     returns java.util.List<ehealth.ws.MeasureDefinition>
     */
    @WebMethod
    @WebResult(name = "Measures", targetNamespace = "")
    @RequestWrapper(localName = "getMeasuresDefinition", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetMeasuresDefinition")
    @ResponseWrapper(localName = "getMeasuresDefinitionResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetMeasuresDefinitionResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/getMeasuresDefinitionRequest", output = "http://ws.ehealth/LifestyleCoach/getMeasuresDefinitionResponse")
    public List<MeasureDefinition> getMeasuresDefinition();

    /**
     * 
     * @param username
     * @param key
     * @return
     *     returns ehealth.ws.UserProfile
     */
    @WebMethod
    @WebResult(name = "profile", targetNamespace = "")
    @RequestWrapper(localName = "getUserProfile", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetUserProfile")
    @ResponseWrapper(localName = "getUserProfileResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetUserProfileResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/getUserProfileRequest", output = "http://ws.ehealth/LifestyleCoach/getUserProfileResponse")
    public UserProfile getUserProfile(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @param username
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "logout", targetNamespace = "")
    @RequestWrapper(localName = "logout", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.LogoutResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/logoutRequest", output = "http://ws.ehealth/LifestyleCoach/logoutResponse")
    public String logout(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "Key", targetNamespace = "")
        String key);

    /**
     * 
     * @param uid
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "deleteUser", targetNamespace = "")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.DeleteUserResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/deleteUserRequest", output = "http://ws.ehealth/LifestyleCoach/deleteUserResponse")
    public int deleteUser(
        @WebParam(name = "Uid", targetNamespace = "")
        int uid);

    /**
     * 
     * @param user
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "NewUser", targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.CreateUserResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/createUserRequest", output = "http://ws.ehealth/LifestyleCoach/createUserResponse")
    public int createUser(
        @WebParam(name = "user", targetNamespace = "")
        UserProfile user);

    /**
     * 
     * @return
     *     returns java.util.List<ehealth.ws.UserProfile>
     */
    @WebMethod
    @WebResult(name = "Users", targetNamespace = "")
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetAllUsersResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/getAllUsersRequest", output = "http://ws.ehealth/LifestyleCoach/getAllUsersResponse")
    public List<UserProfile> getAllUsers();

    /**
     * 
     * @param username
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "login", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.LoginResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/loginRequest", output = "http://ws.ehealth/LifestyleCoach/loginResponse")
    public String login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
