
package ehealth.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LifestyleCoach", targetNamespace = "http://ws.ehealth/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LifestyleCoach {


    /**
     * 
     * @return
     *     returns java.util.List<ehealth.ws.MeasureDefinition>
     */
    @WebMethod
    @WebResult(name = "Measures", targetNamespace = "")
    @RequestWrapper(localName = "getMeasuresDefinition", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetMeasuresDefinition")
    @ResponseWrapper(localName = "getMeasuresDefinitionResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetMeasuresDefinitionResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/getMeasuresDefinitionRequest", output = "http://ws.ehealth/LifestyleCoach/getMeasuresDefinitionResponse")
    public List<MeasureDefinition> getMeasuresDefinition();

    /**
     * 
     * @param username
     * @param key
     * @return
     *     returns java.util.List<ehealth.ws.Goal>
     */
    @WebMethod
    @WebResult(name = "CurrentGoal", targetNamespace = "")
    @RequestWrapper(localName = "getCurrentGoal", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetCurrentGoal")
    @ResponseWrapper(localName = "getCurrentGoalResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetCurrentGoalResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/getCurrentGoalRequest", output = "http://ws.ehealth/LifestyleCoach/getCurrentGoalResponse")
    public List<Goal> getCurrentGoal(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @param username
     * @param key
     * @return
     *     returns ehealth.ws.UserProfile
     */
    @WebMethod
    @WebResult(name = "profile", targetNamespace = "")
    @RequestWrapper(localName = "getUserProfile", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetUserProfile")
    @ResponseWrapper(localName = "getUserProfileResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetUserProfileResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/getUserProfileRequest", output = "http://ws.ehealth/LifestyleCoach/getUserProfileResponse")
    public UserProfile getUserProfile(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @param username
     * @param key
     * @return
     *     returns java.util.List<ehealth.ws.LifeStatus>
     */
    @WebMethod
    @WebResult(name = "viewLifeStatus", targetNamespace = "")
    @RequestWrapper(localName = "viewLifeStatus", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.ViewLifeStatus")
    @ResponseWrapper(localName = "viewLifeStatusResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.ViewLifeStatusResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/viewLifeStatusRequest", output = "http://ws.ehealth/LifestyleCoach/viewLifeStatusResponse")
    public List<LifeStatus> viewLifeStatus(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @return
     *     returns java.util.List<ehealth.ws.UserProfile>
     */
    @WebMethod
    @WebResult(name = "Users", targetNamespace = "")
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetAllUsersResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/getAllUsersRequest", output = "http://ws.ehealth/LifestyleCoach/getAllUsersResponse")
    public List<UserProfile> getAllUsers();

    /**
     * 
     * @param username
     * @param user
     * @param key
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "updateUser", targetNamespace = "")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.UpdateUserResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/updateUserRequest", output = "http://ws.ehealth/LifestyleCoach/updateUserResponse")
    public int updateUser(
        @WebParam(name = "user", targetNamespace = "")
        UserProfile user,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @param username
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "login", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.LoginResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/loginRequest", output = "http://ws.ehealth/LifestyleCoach/loginResponse")
    public String login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param username
     * @param measureType
     * @param value
     * @param key
     * @return
     *     returns ehealth.ws.LifeStatus
     */
    @WebMethod
    @WebResult(name = "LifeStatus", targetNamespace = "")
    @RequestWrapper(localName = "addLifeStatus", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.AddLifeStatus")
    @ResponseWrapper(localName = "addLifeStatusResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.AddLifeStatusResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/addLifeStatusRequest", output = "http://ws.ehealth/LifestyleCoach/addLifeStatusResponse")
    public LifeStatus addLifeStatus(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key,
        @WebParam(name = "value", targetNamespace = "")
        Double value,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType);

    /**
     * 
     * @param username
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "logout", targetNamespace = "")
    @RequestWrapper(localName = "logout", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.LogoutResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/logoutRequest", output = "http://ws.ehealth/LifestyleCoach/logoutResponse")
    public String logout(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "Key", targetNamespace = "")
        String key);

    /**
     * 
     * @param username
     * @param goalId
     * @param key
     * @return
     *     returns ehealth.ws.Goal
     */
    @WebMethod
    @WebResult(name = "setGoal", targetNamespace = "")
    @RequestWrapper(localName = "setGoal", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.SetGoal")
    @ResponseWrapper(localName = "setGoalResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.SetGoalResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/setGoalRequest", output = "http://ws.ehealth/LifestyleCoach/setGoalResponse")
    public Goal setGoal(
        @WebParam(name = "GoalId", targetNamespace = "")
        Goal goalId,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @param username
     * @param goalid
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "deleteGoal", targetNamespace = "")
    @RequestWrapper(localName = "deleteGoal", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.DeleteGoal")
    @ResponseWrapper(localName = "deleteGoalResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.DeleteGoalResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/deleteGoalRequest", output = "http://ws.ehealth/LifestyleCoach/deleteGoalResponse")
    public String deleteGoal(
        @WebParam(name = "Goalid", targetNamespace = "")
        int goalid,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @param username
     * @param key
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "loginCheck", targetNamespace = "")
    @RequestWrapper(localName = "loginCheck", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.LoginCheck")
    @ResponseWrapper(localName = "loginCheckResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.LoginCheckResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/loginCheckRequest", output = "http://ws.ehealth/LifestyleCoach/loginCheckResponse")
    public int loginCheck(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @param user
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "NewUser", targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.CreateUserResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/createUserRequest", output = "http://ws.ehealth/LifestyleCoach/createUserResponse")
    public int createUser(
        @WebParam(name = "user", targetNamespace = "")
        UserProfile user);

    /**
     * 
     * @param username
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMotivation")
    @WebResult(name = "Motivation", targetNamespace = "")
    @RequestWrapper(localName = "GetMotivation", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetMotivation")
    @ResponseWrapper(localName = "GetMotivationResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetMotivationResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/GetMotivationRequest", output = "http://ws.ehealth/LifestyleCoach/GetMotivationResponse")
    public String getMotivation(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @param username
     * @param key
     * @param goal
     * @return
     *     returns ehealth.ws.Goal
     */
    @WebMethod(operationName = "GoalUpdate")
    @WebResult(name = "GoalUpdate", targetNamespace = "")
    @RequestWrapper(localName = "GoalUpdate", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GoalUpdate")
    @ResponseWrapper(localName = "GoalUpdateResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GoalUpdateResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/GoalUpdateRequest", output = "http://ws.ehealth/LifestyleCoach/GoalUpdateResponse")
    public Goal goalUpdate(
        @WebParam(name = "goal", targetNamespace = "")
        Goal goal,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

    /**
     * 
     * @param uid
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "deleteUser", targetNamespace = "")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.DeleteUserResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/deleteUserRequest", output = "http://ws.ehealth/LifestyleCoach/deleteUserResponse")
    public int deleteUser(
        @WebParam(name = "Uid", targetNamespace = "")
        int uid);

    /**
     * 
     * @param username
     * @param key
     * @return
     *     returns ehealth.ws.Goal
     */
    @WebMethod(operationName = "GetPushMessage")
    @WebResult(name = "PushMessage", targetNamespace = "")
    @RequestWrapper(localName = "GetPushMessage", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetPushMessage")
    @ResponseWrapper(localName = "GetPushMessageResponse", targetNamespace = "http://ws.ehealth/", className = "ehealth.ws.GetPushMessageResponse")
    @Action(input = "http://ws.ehealth/LifestyleCoach/GetPushMessageRequest", output = "http://ws.ehealth/LifestyleCoach/GetPushMessageResponse")
    public Goal getPushMessage(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "key", targetNamespace = "")
        String key);

}
